[package]
name = "dynamic_pub_sub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO(luca) change this to the correct version once dynamic message support is released on crates.io
rclrs = { git = "https://github.com/luca-della-vedova/ros2_rust", branch = "dynamic_messages" }
anyhow = {version = "1", features = ["backtrace"]}
